#!/usr/bin/env python3
"""
Generates _version.py with the current git commit hash and date.
Run this before PyInstaller so the build info is baked into the exe.
"""
import subprocess
import sys
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))

    try:
        commit = subprocess.check_output(
            ['git', 'log', '-1', '--format=%h'],
            cwd=script_dir,
            stderr=subprocess.DEVNULL,
            text=True
        ).strip()
        date = subprocess.check_output(
            ['git', 'log', '-1', '--format=%cd', '--date=format:%d %b %Y'],
            cwd=script_dir,
            stderr=subprocess.DEVNULL,
            text=True
        ).strip()
    except Exception as e:
        print(f'WARNING: Could not read git info: {e}')
        commit = 'unknown'
        date = 'unknown'

    out_path = os.path.join(script_dir, '_version.py')
    with open(out_path, 'w') as f:
        f.write(f'# Auto-generated by _generate_version.py - do not edit\n')
        f.write(f'BUILD_COMMIT = "{commit}"\n')
        f.write(f'BUILD_DATE = "{date}"\n')

    print(f'_version.py written: {commit} · {date}')

if __name__ == '__main__':
    main()
