blank_issues_enabled: false
contact_links:
  - name: Question or help
    url: https://github.com/mrdavearms/bulk-pdf-extractor-and-generator/discussions/categories/q-a
    about: Ask questions and get help from the community in Discussions
